### PR TITLE
Message validation leftovers

### PR DESCRIPTION
**Pull request by nkryuchkov**
Leftovers:

- [x] Investigate rejected messages
    - [x] `message is duplicated` (round change)
    - [x] `duplicated proposal with different data`
    - [x] `signer is not leader`
- [x] Remove the commented-out code in `network/p2p/test_utils.go` (https://github.com/ssvlabs/ssv/pull/1393#discussion_r1650112555, https://github.com/ssvlabs/ssv/pull/1393#discussion_r1667675468)
- [x] Replace treemap with an array (https://github.com/ssvlabs/ssv/pull/1393#discussion_r1664436261)
- [x] Optimize constructing validator indices (https://github.com/ssvlabs/ssv/pull/1393#discussion_r1667681686)
- [ ] Check `ValidatorRegistration` duty (https://github.com/ssvlabs/ssv/pull/1393#discussion_r1667687976)
- [x] Check all constants (https://github.com/ssvlabs/ssv/pull/1393#discussion_r1670160504)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
It's likely going to be superseded with separate PRs for each leftover and closed

**Comment by nkryuchkov** [comment]
https://github.com/ssvlabs/ssv/pull/1456

**Comment by nkryuchkov** [comment]
https://github.com/ssvlabs/ssv/pull/1457

**Comment by nkryuchkov** [comment]
https://github.com/ssvlabs/ssv/pull/1462

**Comment by nkryuchkov** [comment]
https://github.com/ssvlabs/ssv/pull/1458

**Comment by y0sher** [comment]
Anything here not merged yet? if everything merged lets close this.

**Comment by nkryuchkov** [comment]
@y0sher only `Check ValidatorRegistration duty` is left but it will be done in a separate PR. I'm closing this one

**Comment by nkryuchkov** [comment]
https://github.com/ssvlabs/ssv/pull/1468

**Pull request closed without merging**
